### ISSUE TITLE
Error: Cannot find module 'unirest'

### ISSUE THREAD

**Issue by Freekers** [idiidk/vakantieveilingen-bot#1]
Hi there,

I'm trying to run this on Windows 10 64-bit with NodeJS v12.6.0
I've followed the setup in the readme. When running `node index.js` I get the following error:

```
D:\git\vakantieveilingen-bot>node index.js
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module 'unirest'
Require stack:
- D:\git\vakantieveilingen-bot\vvapi.js
- D:\git\vakantieveilingen-bot\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (D:\git\vakantieveilingen-bot\vvapi.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\git\\vakantieveilingen-bot\\vvapi.js',
    'D:\\git\\vakantieveilingen-bot\\index.js'
  ]
}
```

I tried installing `unirest` like so: `npm install -g unirest` but that did not solve the issue, neither did installing `request` in the same manner.

Any idea what the culprit might be?

Thank you!

**Comment by idiidk** [comment]
Oh frick, I forgot to add unirest to the package.json xd. This is a really old project, and I don't even know if it still works. I'll take a look for you.

**Comment by idiidk** [comment]
Just run ```npm i``` again before you run index. And I would advise you to remove that global unirest package, it can cause problems ;)

**Comment by Freekers** [comment]
Thanks for the quick response! I uninstalled the global unirest package, did a git pull and ran `npm i` before running index, but I'm getting the same error. I also re-ran `npm install` but sadly it made no difference. Thanks!
